package co.edu.udea.entity;
// Generated 4/11/2016 10:52:06 AM by Hibernate Tools 4.3.1


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Products generated by hbm2java
 */
@Entity
@Table(name="products"
    ,catalog="udeacommerce"
)
public class Products  implements java.io.Serializable {


     private String id;
     private String name;
     private Double price;
     private String image;

    public Products() {
    }

	
    public Products(String id) {
        this.id = id;
    }
    public Products(String id, String name, Double price, String image) {
       this.id = id;
       this.name = name;
       this.price = price;
       this.image = image;
    }
   
     @Id 

    
    @Column(name="id", unique=true, nullable=false, length=7)
    public String getId() {
        return this.id;
    }
    
    public void setId(String id) {
        this.id = id;
    }

    
    @Column(name="name", length=50)
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }

    
    @Column(name="price", precision=22, scale=0)
    public Double getPrice() {
        return this.price;
    }
    
    public void setPrice(Double price) {
        this.price = price;
    }

    
    @Column(name="image", length=50)
    public String getImage() {
        return this.image;
    }
    
    public void setImage(String image) {
        this.image = image;
    }




}


